openapi: 3.0.0
info:
  title: Narratives Project API
  description: API for managing narratives, stories, and tags
  version: 1.0.0
paths:
  /trpc/addStory:
    post:
      summary: Add a new story
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddStoryInput'
      responses:
        '200':
          description: Story added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddStoryResponse'
  /trpc/addNarrative:
    post:
      summary: Add a new narrative
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddNarrativeInput'
      responses:
        '200':
          description: Narrative added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddNarrativeResponse'
  /trpc/addTag:
    post:
      summary: Add a new tag
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddTagInput'
      responses:
        '200':
          description: Tag added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddTagResponse'
  /trpc/addTagsToNarrative:
    post:
      summary: Add tags to a narrative
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddTagToNarrativeInput'
      responses:
        '200':
          description: Tags added to narrative successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddTagToNarrativeResponse'
  /trpc/getTagList:
    get:
      summary: Get list of tags
      parameters:
        - name: searchString
          in: query
          schema:
            type: string
        - name: userId
          in: query
          schema:
            type: string
      responses:
        '200':
          description: List of tags
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AddTagResponse'
  /trpc/addStoryToNarrative:
    post:
      summary: Add a story to a narrative
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddStoryToNarrativeInput'
      responses:
        '200':
          description: Story added to narrative successfully
  /trpc/getNarrativesList:
    get:
      summary: Get list of narratives
      responses:
        '200':
          description: List of narratives
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AddNarrativeResponse'
  /trpc/getNarrativeStories:
    get:
      summary: Get stories for a narrative
      parameters:
        - name: narrativeId
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Narrative with stories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NarrativeStoryEntry'
components:
  schemas:
    AddStoryInput:
      type: object
      required:
        - storyTitle
        - date
        - summary
        - link
      properties:
        storyTitle:
          type: string
          maxLength: 250
        date:
          type: string
          format: date-time
        summary:
          type: string
          maxLength: 1000
        link:
          type: string
    AddStoryResponse:
      type: object
      properties:
        _id:
          type: string
        storyTitle:
          type: string
        date:
          type: string
          format: date-time
        link:
          type: string
        summary:
          type: string
        createdAt:
          type: string
          format: date-time
        createdBy:
          type: string
    AddNarrativeInput:
      type: object
      required:
        - title
        - abbreviation
        - summary
      properties:
        title:
          type: string
          maxLength: 250
        abbreviation:
          type: string
          maxLength: 12
        summary:
          type: string
          maxLength: 5000
    AddNarrativeResponse:
      type: object
      properties:
        _id:
          type: string
        title:
          type: string
        abbreviation:
          type: string
        summary:
          type: string
        createdAt:
          type: string
          format: date-time
        createdBy:
          type: string
        tags:
          type: array
          items:
            type: string
    AddTagInput:
      type: object
      required:
        - tagName
        - tagText
      properties:
        tagName:
          type: string
          maxLength: 30
        tagText:
          type: string
          maxLength: 100
    AddTagResponse:
      type: object
      properties:
        _id:
          type: string
        tagName:
          type: string
        tagTitle:
          type: string
        createdAt:
          type: string
          format: date-time
        createdBy:
          type: string
    AddTagToNarrativeInput:
      type: object
      required:
        - narrativeId
        - tags
      properties:
        narrativeId:
          type: string
        tags:
          type: array
          items:
            type: string
    AddTagToNarrativeResponse:
      type: object
      properties:
        _id:
          type: string
        title:
          type: string
        abbreviation:
          type: string
        summary:
          type: string
        createdAt:
          type: string
          format: date-time
        createdBy:
          type: string
        tags:
          type: array
          items:
            type: string
    AddStoryToNarrativeInput:
      type: object
      required:
        - narrativeId
        - storyId
      properties:
        narrativeId:
          type: string
        storyId:
          type: string
    NarrativeStoryEntry:
      type: object
      properties:
        _id:
          type: string
        title:
          type: string
        abbreviation:
          type: string
        summary:
          type: string
        createdAt:
          type: string
          format: date-time
        createdBy:
          type: string
        tags:
          type: array
          items:
            type: string
        stories:
          type: array
          items:
            $ref: '#/components/schemas/StorySchema'
    StorySchema:
      type: object
      properties:
        _id:
          type: string
        storyTitle:
          type: string
        date:
          type: string
          format: date-time
        link:
          type: string
        summary:
          type: string
        createdAt:
          type: string
          format: date-time
        createdBy:
          type: string
        tags:
          type: array
          items:
            type: string